defaultPortal: cuenta-de-prueba-de-desarrollador-1
portals:
  - name: cuenta-de-prueba-de-desarrollador-1
    portalId: 145589641
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CO-3hrKpMhIRAA0AQAAA4G0DQAJYAgEAAPgYiYu2RSCb9LAiKO7pDDIUQ_p16Pf9-h-S_ZYGcsgsrD_USCw6TAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAgAwAAAAAAPP4DAAAAAAAAAAwEAAAAAAAAAAAAABBCFIUKX59ZFH3yFEUIu82yeiTxGOCeSgNldTFSAFoAYAA
        expiresAt: '2024-10-16T16:55:35.192Z'
    accountType: DEVELOPER_TEST
    personalAccessKey: >-
      CiRldTEtYzcxOC1lOGNmLTRlNWEtYTlhZC0xYzM2MjUzNGVlNjYQiYu2RRib9LAiKhkABeaRgta_Pliq_UH5YSprWQBzHYb4TtTDSgNldTE
    parentAccountId: 145587897
