defaultPortal: cuenta-de-prueba-de-desarrollador-1
portals:
  - name: cuenta-de-prueba-de-desarrollador-1
    portalId: 145589641
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLfgr66pMhIRAA0AQAAA4G0DQAJYAgEAAPgYiYu2RSCb9LAiKO7pDDIUYh7tF1SrWjFLvkfN3aFnMzZyQSI6TAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAgAwAAAAAAPP4DAAAAAAAAAAwEAAAAAAAAAAAAABBCFKDGlypLTYWAZ0BhZ7Yw-61R5YR7SgNldTFSAFoAYAA
        expiresAt: '2024-10-16T14:47:03.515Z'
    accountType: DEVELOPER_TEST
    personalAccessKey: >-
      CiRldTEtYzcxOC1lOGNmLTRlNWEtYTlhZC0xYzM2MjUzNGVlNjYQiYu2RRib9LAiKhkABeaRgta_Pliq_UH5YSprWQBzHYb4TtTDSgNldTE
    parentAccountId: 145587897
