defaultPortal: cuenta-de-prueba-de-desarrollador-1
portals:
  - name: cuenta-de-prueba-de-desarrollador-1
    portalId: 145589641
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJWE86ypMhIRAA0AQAAA4G0DQAJYAgEAAPgYiYu2RSCb9LAiKO7pDDIUITE8A8bEZvookmcQauvIfo1lZx86TAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAgAwAAAAAAPP4DAAAAAAAAAAwEAAAAAAAAAAAAABBCFHYO4TbbR3SGU7B2b8s8Yj6_e2QTSgNldTFSAFoAYAA
        expiresAt: '2024-10-16T13:55:31.515Z'
    accountType: DEVELOPER_TEST
    personalAccessKey: >-
      CiRldTEtYzcxOC1lOGNmLTRlNWEtYTlhZC0xYzM2MjUzNGVlNjYQiYu2RRib9LAiKhkABeaRgta_Pliq_UH5YSprWQBzHYb4TtTDSgNldTE
    parentAccountId: 145587897
